"""quotes table

Revision ID: 9b859af14831
Revises: 
Create Date: 2019-01-05 07:17:07.324501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b859af14831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('forename', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('sort_code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.Column('_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_email'), 'quotes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_email'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
